version: '2'
services:
    lexisnexishack2017-app:
        image: lexisnexishack2017
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://lexisnexishack2017-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lexisnexishack2017-mssql:
        extends:
            file: mssql.yml
            service: lexisnexishack2017-mssql
